apiVersion: v1
description: coreos-version-checker Helm chart for Kubernetes
name: coreos-version-checker
version: 0.0.0  # this entry can be left untouched as it is automatically handled by Jenkins pipeline
