# Default values for coreos-version-checker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isDaemon: "true"
replicaCount: 1
image:
  repository: coco/coreos-version-checker
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 16Mi
  limits:
    memory: 128Mi
